2022-04-21 01:13:53,692 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-04-21 01:13:53,693 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\singh\PycharmProjects\1st prog\venv\lib\site-packages\instabot\bot\bot.py
2022-04-21 01:13:53,694 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-04-21 01:13:54,309 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-04-21 01:13:54,309 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-04-21 01:13:54,309 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-04-21 01:13:54,309 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2022-04-21 01:18:55,102 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [400]>
2022-04-21 01:18:55,102 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"","status":"fail"}'
2022-04-21 01:18:55,102 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-04-21 01:18:55,102 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: 
2022-04-21 01:18:55,102 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: {}
2022-04-21 01:18:55,637 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-04-21 01:18:56,166 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-04-21 01:18:56,700 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-04-21 01:19:03,996 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-04-21 01:19:03,996 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXG8lf24E7IXp_fB5qZmOpyh_Uu1SVJtiYLUbkoCmXwrjRdOZQqmTBCVEz_AQmPjK0bCGcQ/LBFsa4Kk9Re6EUSy/","api_path":"/challenge/AXG8lf24E7IXp_fB5qZmOpyh_Uu1SVJtiYLUbkoCmXwrjRdOZQqmTBCVEz_AQmPjK0bCGcQ/LBFsa4Kk9Re6EUSy/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-04-21 01:19:03,996 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-04-21 01:19:03,996 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-04-21 01:19:03,996 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-04-21 01:19:08,251 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-04-21 01:19:08,251 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Nilaroom.jpg' is not uploaded.
